//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Entity.proto
namespace Contract.Entity
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserEntity")]
  public partial class UserEntity : global::ProtoBuf.IExtensible
  {
    public UserEntity() {}
    

    private string _UserID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private string _HeadImg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"HeadImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string HeadImg
    {
      get { return _HeadImg; }
      set { _HeadImg = value; }
    }

    private int _GoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"GoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GoldCoin
    {
      get { return _GoldCoin; }
      set { _GoldCoin = value; }
    }

    private int _Diamond = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }

    private int _SelectRole = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"SelectRole", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SelectRole
    {
      get { return _SelectRole; }
      set { _SelectRole = value; }
    }

    private string _HaveRole = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"HaveRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string HaveRole
    {
      get { return _HaveRole; }
      set { _HaveRole = value; }
    }

    private int _Strength = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Strength", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Strength
    {
      get { return _Strength; }
      set { _Strength = value; }
    }

    private int _MaxStrength = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"MaxStrength", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxStrength
    {
      get { return _MaxStrength; }
      set { _MaxStrength = value; }
    }

    private int _StarsNum = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"StarsNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StarsNum
    {
      get { return _StarsNum; }
      set { _StarsNum = value; }
    }

    private int _ClearanceNum = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"ClearanceNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ClearanceNum
    {
      get { return _ClearanceNum; }
      set { _ClearanceNum = value; }
    }

    private int _BuyStrengthNum = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"BuyStrengthNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BuyStrengthNum
    {
      get { return _BuyStrengthNum; }
      set { _BuyStrengthNum = value; }
    }

    private int _MaxSkill = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"MaxSkill", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxSkill
    {
      get { return _MaxSkill; }
      set { _MaxSkill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HurdleLevelEntity")]
  public partial class HurdleLevelEntity : global::ProtoBuf.IExtensible
  {
    public HurdleLevelEntity() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private int _BossID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"BossID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BossID
    {
      get { return _BossID; }
      set { _BossID = value; }
    }

    private int _MonsterID = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"MonsterID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MonsterID
    {
      get { return _MonsterID; }
      set { _MonsterID = value; }
    }

    private int _MaxGoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"MaxGoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxGoldCoin
    {
      get { return _MaxGoldCoin; }
      set { _MaxGoldCoin = value; }
    }

    private int _MonsterGoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MonsterGoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MonsterGoldCoin
    {
      get { return _MonsterGoldCoin; }
      set { _MonsterGoldCoin = value; }
    }

    private string _Prop = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Prop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Prop
    {
      get { return _Prop; }
      set { _Prop = value; }
    }

    private int _StandardTime = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"StandardTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StandardTime
    {
      get { return _StandardTime; }
      set { _StandardTime = value; }
    }

    private int _StandardGoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"StandardGoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StandardGoldCoin
    {
      get { return _StandardGoldCoin; }
      set { _StandardGoldCoin = value; }
    }

    private int _Energy = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Energy", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Energy
    {
      get { return _Energy; }
      set { _Energy = value; }
    }

    private int _OpenStar = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"OpenStar", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int OpenStar
    {
      get { return _OpenStar; }
      set { _OpenStar = value; }
    }

    private int _Lv = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Lv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Lv
    {
      get { return _Lv; }
      set { _Lv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PassInfoEntity")]
  public partial class PassInfoEntity : global::ProtoBuf.IExtensible
  {
    public PassInfoEntity() {}
    

    private int _PassID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PassID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PassID
    {
      get { return _PassID; }
      set { _PassID = value; }
    }

    private int _StarsNum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"StarsNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StarsNum
    {
      get { return _StarsNum; }
      set { _StarsNum = value; }
    }

    private string _Remark = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Remark
    {
      get { return _Remark; }
      set { _Remark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleSkillEntity")]
  public partial class RoleSkillEntity : global::ProtoBuf.IExtensible
  {
    public RoleSkillEntity() {}
    

    private int _RoleID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }

    private int _SkillID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SkillID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SkillID
    {
      get { return _SkillID; }
      set { _SkillID = value; }
    }

    private int _Num = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }

    private int _Lv = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Lv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Lv
    {
      get { return _Lv; }
      set { _Lv = value; }
    }

    private bool _Selected = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Selected", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Selected
    {
      get { return _Selected; }
      set { _Selected = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrizeEntity")]
  public partial class PrizeEntity : global::ProtoBuf.IExtensible
  {
    public PrizeEntity() {}
    

    private int _Prize = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Prize", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Prize
    {
      get { return _Prize; }
      set { _Prize = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildEntity")]
  public partial class GuildEntity : global::ProtoBuf.IExtensible
  {
    public GuildEntity() {}
    

    private int _ID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private int _ActiveValue = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ActiveValue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ActiveValue
    {
      get { return _ActiveValue; }
      set { _ActiveValue = value; }
    }

    private string _PresidentID = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"PresidentID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PresidentID
    {
      get { return _PresidentID; }
      set { _PresidentID = value; }
    }

    private int _CurrentMember = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"CurrentMember", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CurrentMember
    {
      get { return _CurrentMember; }
      set { _CurrentMember = value; }
    }

    private int _MaxMember = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MaxMember", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxMember
    {
      get { return _MaxMember; }
      set { _MaxMember = value; }
    }

    private bool _IsName = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"IsName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsName
    {
      get { return _IsName; }
      set { _IsName = value; }
    }

    private int _OldRanking = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"OldRanking", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int OldRanking
    {
      get { return _OldRanking; }
      set { _OldRanking = value; }
    }

    private int _NewRanking = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"NewRanking", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int NewRanking
    {
      get { return _NewRanking; }
      set { _NewRanking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildMemberEntity")]
  public partial class GuildMemberEntity : global::ProtoBuf.IExtensible
  {
    public GuildMemberEntity() {}
    

    private string _MemberID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MemberID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MemberID
    {
      get { return _MemberID; }
      set { _MemberID = value; }
    }

    private string _MemberName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"MemberName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MemberName
    {
      get { return _MemberName; }
      set { _MemberName = value; }
    }

    private int _ActiveValue = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ActiveValue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ActiveValue
    {
      get { return _ActiveValue; }
      set { _ActiveValue = value; }
    }

    private bool _IsSign = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"IsSign", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsSign
    {
      get { return _IsSign; }
      set { _IsSign = value; }
    }

    private bool _IsOnLine = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"IsOnLine", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsOnLine
    {
      get { return _IsOnLine; }
      set { _IsOnLine = value; }
    }

    private string _DownLineTime = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"DownLineTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DownLineTime
    {
      get { return _DownLineTime; }
      set { _DownLineTime = value; }
    }

    private int _GuildID = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"GuildID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GuildID
    {
      get { return _GuildID; }
      set { _GuildID = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}