//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Hall.proto
// Note: requires additional types generated from: Entity.proto
namespace Contract.Hall
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResultContract")]
  public partial class LoginResultContract : global::ProtoBuf.IExtensible
  {
    public LoginResultContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }

    private Contract.Entity.UserEntity _UserInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UserInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Contract.Entity.UserEntity UserInfo
    {
      get { return _UserInfo; }
      set { _UserInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<Contract.Entity.RoleSkillEntity> _RoleSkillList = new global::System.Collections.Generic.List<Contract.Entity.RoleSkillEntity>();
    [global::ProtoBuf.ProtoMember(3, Name=@"RoleSkillList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Contract.Entity.RoleSkillEntity> RoleSkillList
    {
      get { return _RoleSkillList; }
    }
  

    private int _CostGoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"CostGoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CostGoldCoin
    {
      get { return _CostGoldCoin; }
      set { _CostGoldCoin = value; }
    }

    private int _CostDiamond = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"CostDiamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CostDiamond
    {
      get { return _CostDiamond; }
      set { _CostDiamond = value; }
    }

    private string _EatBunTime = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"EatBunTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string EatBunTime
    {
      get { return _EatBunTime; }
      set { _EatBunTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginContract")]
  public partial class LoginContract : global::ProtoBuf.IExtensible
  {
    public LoginContract() {}
    

    private string _UserID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }

    private string _Pwd = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Pwd
    {
      get { return _Pwd; }
      set { _Pwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterContract")]
  public partial class RegisterContract : global::ProtoBuf.IExtensible
  {
    public RegisterContract() {}
    

    private string _UserID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }

    private string _Pwd = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Pwd
    {
      get { return _Pwd; }
      set { _Pwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultRegisterContract")]
  public partial class ResultRegisterContract : global::ProtoBuf.IExtensible
  {
    public ResultRegisterContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultCreateUserNameContract")]
  public partial class ResultCreateUserNameContract : global::ProtoBuf.IExtensible
  {
    public ResultCreateUserNameContract() {}
    

    private string _UserName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetHurdleLevelContract")]
  public partial class GetHurdleLevelContract : global::ProtoBuf.IExtensible
  {
    public GetHurdleLevelContract() {}
    
    private readonly global::System.Collections.Generic.List<Contract.Entity.PassInfoEntity> _OrdinaryPassInfoList = new global::System.Collections.Generic.List<Contract.Entity.PassInfoEntity>();
    [global::ProtoBuf.ProtoMember(1, Name=@"OrdinaryPassInfoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Contract.Entity.PassInfoEntity> OrdinaryPassInfoList
    {
      get { return _OrdinaryPassInfoList; }
    }
  
    private readonly global::System.Collections.Generic.List<Contract.Entity.PassInfoEntity> _ElitePassInfoList = new global::System.Collections.Generic.List<Contract.Entity.PassInfoEntity>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ElitePassInfoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Contract.Entity.PassInfoEntity> ElitePassInfoList
    {
      get { return _ElitePassInfoList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LuckDrawContract")]
  public partial class LuckDrawContract : global::ProtoBuf.IExtensible
  {
    public LuckDrawContract() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultLuckDrawContract")]
  public partial class ResultLuckDrawContract : global::ProtoBuf.IExtensible
  {
    public ResultLuckDrawContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }

    private Contract.Entity.PrizeEntity _PrizeInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PrizeInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Contract.Entity.PrizeEntity PrizeInfo
    {
      get { return _PrizeInfo; }
      set { _PrizeInfo = value; }
    }

    private int _GoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"GoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GoldCoin
    {
      get { return _GoldCoin; }
      set { _GoldCoin = value; }
    }

    private int _Diamond = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyRoleContract")]
  public partial class BuyRoleContract : global::ProtoBuf.IExtensible
  {
    public BuyRoleContract() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private int _RoleID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultBuyRoleContract")]
  public partial class ResultBuyRoleContract : global::ProtoBuf.IExtensible
  {
    public ResultBuyRoleContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private int _RoleID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }

    private int _GoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"GoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GoldCoin
    {
      get { return _GoldCoin; }
      set { _GoldCoin = value; }
    }

    private int _Diamond = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }
    private readonly global::System.Collections.Generic.List<Contract.Entity.RoleSkillEntity> _RoleSkillList = new global::System.Collections.Generic.List<Contract.Entity.RoleSkillEntity>();
    [global::ProtoBuf.ProtoMember(6, Name=@"RoleSkillList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Contract.Entity.RoleSkillEntity> RoleSkillList
    {
      get { return _RoleSkillList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillUpgradeContract")]
  public partial class SkillUpgradeContract : global::ProtoBuf.IExtensible
  {
    public SkillUpgradeContract() {}
    

    private int _SkillID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SkillID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SkillID
    {
      get { return _SkillID; }
      set { _SkillID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultSkillUpgradeContract")]
  public partial class ResultSkillUpgradeContract : global::ProtoBuf.IExtensible
  {
    public ResultSkillUpgradeContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }

    private int _GoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"GoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GoldCoin
    {
      get { return _GoldCoin; }
      set { _GoldCoin = value; }
    }

    private int _Diamond = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectRoleContract")]
  public partial class SelectRoleContract : global::ProtoBuf.IExtensible
  {
    public SelectRoleContract() {}
    

    private int _RoleID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultSelectRoleContract")]
  public partial class ResultSelectRoleContract : global::ProtoBuf.IExtensible
  {
    public ResultSelectRoleContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectSkillContract")]
  public partial class SelectSkillContract : global::ProtoBuf.IExtensible
  {
    public SelectSkillContract() {}
    

    private int _SkillID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SkillID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SkillID
    {
      get { return _SkillID; }
      set { _SkillID = value; }
    }

    private int _FormerID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"FormerID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int FormerID
    {
      get { return _FormerID; }
      set { _FormerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultSelectSkillContract")]
  public partial class ResultSelectSkillContract : global::ProtoBuf.IExtensible
  {
    public ResultSelectSkillContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuySkillCountContract")]
  public partial class BuySkillCountContract : global::ProtoBuf.IExtensible
  {
    public BuySkillCountContract() {}
    

    private int _RoleID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultBuySkillCountContract")]
  public partial class ResultBuySkillCountContract : global::ProtoBuf.IExtensible
  {
    public ResultBuySkillCountContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }

    private int _Diamond = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseSkillContract")]
  public partial class UseSkillContract : global::ProtoBuf.IExtensible
  {
    public UseSkillContract() {}
    

    private int _RoleID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultUseSkillContract")]
  public partial class ResultUseSkillContract : global::ProtoBuf.IExtensible
  {
    public ResultUseSkillContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultStartEatBunContract")]
  public partial class ResultStartEatBunContract : global::ProtoBuf.IExtensible
  {
    public ResultStartEatBunContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _NameList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"NameList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> NameList
    {
      get { return _NameList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetEatBunContract")]
  public partial class GetEatBunContract : global::ProtoBuf.IExtensible
  {
    public GetEatBunContract() {}
    

    private int _ClickCount = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ClickCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ClickCount
    {
      get { return _ClickCount; }
      set { _ClickCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultGetEatBunContract")]
  public partial class ResultGetEatBunContract : global::ProtoBuf.IExtensible
  {
    public ResultGetEatBunContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }

    private int _Strength = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Strength", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Strength
    {
      get { return _Strength; }
      set { _Strength = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateNameContract")]
  public partial class UpdateNameContract : global::ProtoBuf.IExtensible
  {
    public UpdateNameContract() {}
    

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultUpdateNameContract")]
  public partial class ResultUpdateNameContract : global::ProtoBuf.IExtensible
  {
    public ResultUpdateNameContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyPropContract")]
  public partial class BuyPropContract : global::ProtoBuf.IExtensible
  {
    public BuyPropContract() {}
    

    private int _PropID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PropID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PropID
    {
      get { return _PropID; }
      set { _PropID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultBuyPropContract")]
  public partial class ResultBuyPropContract : global::ProtoBuf.IExtensible
  {
    public ResultBuyPropContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }

    private int _Diamond = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }

    private int _PropID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PropID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PropID
    {
      get { return _PropID; }
      set { _PropID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwapGoodsContract")]
  public partial class SwapGoodsContract : global::ProtoBuf.IExtensible
  {
    public SwapGoodsContract() {}
    

    private int _SwapID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SwapID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SwapID
    {
      get { return _SwapID; }
      set { _SwapID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultSwapGoodsContract")]
  public partial class ResultSwapGoodsContract : global::ProtoBuf.IExtensible
  {
    public ResultSwapGoodsContract() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }

    private int _GoldCoin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"GoldCoin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GoldCoin
    {
      get { return _GoldCoin; }
      set { _GoldCoin = value; }
    }

    private int _Diamond = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }

    private int _Strength = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Strength", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Strength
    {
      get { return _Strength; }
      set { _Strength = value; }
    }

    private int _SwapID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"SwapID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SwapID
    {
      get { return _SwapID; }
      set { _SwapID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetVerifyCodeContract")]
  public partial class GetVerifyCodeContract : global::ProtoBuf.IExtensible
  {
    public GetVerifyCodeContract() {}
    

    private string _PhoneNum = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PhoneNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PhoneNum
    {
      get { return _PhoneNum; }
      set { _PhoneNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}